name: Deploy

on:
  push:
    branches: ['master']

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  deploy:
    name: Deploy via rsync
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: up9cloud/action-rsync@e032bd158d5e7d4b3e46fd3263178276fe0126d5 # v1.4
        env:
          HOST: ${{secrets.DEPLOY_HOST}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: ${{secrets.DEPLOY_TARGET}}
          MODE: push
          VERBOSE: true
          PORT: ${{secrets.DEPLOY_PORT}}
          USER: ${{secrets.DEPLOY_USER}}
          ARGS: -avz --exclude-from=.gitignore --exclude=/.git/ --exclude=/.github/
